#!/bin/sh

if grep -q -i -e "WIP" -e "work in progress" $1; then
    read -p "You're about to add a WIP commit, do you want to run the CI? [y|n] " -n 1 -r WIP < /dev/tty
    echo
    if echo $WIP | grep -E '^[Nn]$' > /dev/null; then
        echo "[skip ci]" >> $1
    fi
fi

if ! grep -q -i -e "\[t:[1-99][mh]\]" $1; then
    read -p "You're about to add a commit without reporting how much time you spent. \[t:[1-99][mh]\] Are you sure you want to continue? [y|n] " -n 1 -r LOG_TIME < /dev/tty
    echo
    if echo $LOG_TIME | grep -E '^[Nn]$' > /dev/null; then
        exit 1
    else
      exit 0
    fi
fi
