#!/bin/sh

currentBranch=$(git rev-parse --abbrev-ref HEAD)

if [ $currentBranch == master ]; then
    versionUpdated=$(git diff --staged build.gradle | grep 'version =' > /dev/null 2>&1; echo $?)

    if [ $versionUpdated == 1 ]; then
        echo "Update the version before pushing to master!"
        exit 1;
    fi
fi
